### ISSUE TITLE
请教下这些IOS的表情图片是怎么导出来的呢？

### ISSUE THREAD

**Issue by mopduan** [XadillaX/her-loliji#1]
大侠你好：

   想请教下这些IOS的表情图片是怎么导出来的呢？看到最新版的IOS中国旗类的表情又多了很多，有什么办法可以导出最新的表情？

期待您的回复，谢谢！

**Comment by XadillaX** [comment]
https://github.com/github/gemoji/tree/master/images/emoji/unicode

我是从 GitHub 拿来的。
